import type { Section } from "@/types/content";

/** AISVS 1.0 sections - official chapter/section hierarchy. */
export const sections: Section[] = [
  { id: "C1.1", slug: "c1-1-training-data-origin-and-data-security", title: "Training Data Origin & Data Security", description: "Datasets must be sourced from verifiable origins, tracked across their full lifecycle, and protected against tampering, corruption, and poisoning so that unauthorized modification can be detected.", chapterId: "C1", standardVersion: "1.0" },
  { id: "C1.2", slug: "c1-2-data-labeling-and-annotation-security", title: "Data Labeling and Annotation Security", description: "Labeling and annotation processes must be protected against unauthorized modification, data leakage, and integrity compromise, with access control, auditability, and protected labeling artifacts throughout the training pipeline.", chapterId: "C1", standardVersion: "1.0" },
  { id: "C1.3", slug: "c1-3-training-data-quality-and-security-assurance", title: "Training Data Quality and Security Assurance", description: "Automated validation, poisoning detection, label quality checks, and bias analysis help detect corruption, poisoning, labeling errors, and exploitable dataset patterns before they affect model behavior.", chapterId: "C1", standardVersion: "1.0" },
  { id: "C2.1", slug: "c2-1-prompt-injection-defenses", title: "Prompt Injection Defenses", description: "Defending against prompt injection requires a combination of pattern filters, data classifiers, and instruction hierarchy enforcement.", chapterId: "C2", standardVersion: "1.0" },
  { id: "C2.2", slug: "c2-2-content-and-policy-screening", title: "Content & Policy Screening", description: "Input-side content screening prevents syntactically valid prompts from requesting disallowed content such as policy-violating instructions, harmful material, or restricted information.", chapterId: "C2", standardVersion: "1.0" },
  { id: "C3.1", slug: "c3-1-model-authorization-and-integrity", title: "Model Authorization & Integrity", description: "Only authorized models with verified integrity should reach production environments.", chapterId: "C3", standardVersion: "1.0" },
  { id: "C3.2", slug: "c3-2-model-validation-and-testing", title: "Model Validation & Testing", description: "Models must pass defined security and safety validations before deployment.", chapterId: "C3", standardVersion: "1.0" },
  { id: "C3.3", slug: "c3-3-controlled-deployment-and-rollback", title: "Controlled Deployment & Rollback", description: "Model deployments must be controlled, monitored, and reversible to support lifecycle management.", chapterId: "C3", standardVersion: "1.0" },
  { id: "C3.4", slug: "c3-4-secure-development-practices", title: "Secure Development Practices", description: "Model development environments must be separated from production environments.", chapterId: "C3", standardVersion: "1.0" },
  { id: "C3.5", slug: "c3-5-pipeline-fine-tuning", title: "Pipeline Fine-Tuning", description: "Fine-tuning pipelines are high-privilege operations that can alter deployed model behavior at scale; a compromise at any intermediate stage of a multi-stage pipeline produces a subtly altered artifact that subsequent stages accept.", chapterId: "C3", standardVersion: "1.0" },
  { id: "C4.1", slug: "c4-1-ai-workload-sandboxing-and-validation", title: "AI Workload Sandboxing & Validation", description: "Untrusted AI models must be isolated in secure sandboxes, and sensitive AI workloads protected using trusted execution environments (TEEs) and confidential computing technologies.", chapterId: "C4", standardVersion: "1.0" },
  { id: "C4.2", slug: "c4-2-ai-hardware-security", title: "AI Hardware Security", description: "AI-specific hardware components, including GPUs, TPUs, and specialized AI accelerators, must be secured.", chapterId: "C4", standardVersion: "1.0" },
  { id: "C4.3", slug: "c4-3-edge-and-distributed-ai-security", title: "Edge & Distributed AI Security", description: "Distributed AI deployments, including edge computing, federated learning, and multi-site architectures, must be secured.", chapterId: "C4", standardVersion: "1.0" },
  { id: "C5.1", slug: "c5-1-authentication", title: "Authentication", description: "AI agents and human users accessing resources must be properly authenticated and authorized for their level of access.", chapterId: "C5", standardVersion: "1.0" },
  { id: "C5.2", slug: "c5-2-ai-resource-authorization-and-classification", title: "AI Resource Authorization & Classification", description: "The caller's authorization context must be enforced through AI-specific query pipelines (RAG retrieval, embedding lookups, inference chains) so the system does not return data the caller is not entitled to access.", chapterId: "C5", standardVersion: "1.0" },
  { id: "C5.3", slug: "c5-3-multi-tenant-isolation", title: "Multi-Tenant Isolation", description: "Cross-tenant information leakage through AI-specific shared infrastructure, such as inference caches and shared model state, must be prevented.", chapterId: "C5", standardVersion: "1.0" },
  { id: "C6.1", slug: "c6-1-model-artifact-integrity", title: "Model Artifact Integrity", description: "Third-party model origins must be authenticated and checked for hidden behavior before fine-tuning or deployment, and AI artifacts should be downloaded only from approved sources.", chapterId: "C6", standardVersion: "1.0" },
  { id: "C6.2", slug: "c6-2-ai-bom-and-supply-chain-monitoring", title: "AI BOM & Supply Chain Monitoring", description: "Detailed AI-specific bills of materials must be generated and signed, with readiness to respond to supply chain compromise events.", chapterId: "C6", standardVersion: "1.0" },
  { id: "C7.1", slug: "c7-1-output-format-enforcement", title: "Output Format Enforcement", description: "Model outputs must be structured and validated to reduce downstream injection risk.", chapterId: "C7", standardVersion: "1.0" },
  { id: "C7.2", slug: "c7-2-hallucination-detection-and-mitigation", title: "Hallucination Detection & Mitigation", description: "Potentially inaccurate or fabricated content must be detected so unreliable outputs do not reach users or downstream systems.", chapterId: "C7", standardVersion: "1.0" },
  { id: "C7.3", slug: "c7-3-output-safety", title: "Output Safety", description: "Technical controls must detect and remove unsafe content before it is shown to the user.", chapterId: "C7", standardVersion: "1.0" },
  { id: "C7.4", slug: "c7-4-source-attribution-and-citation-integrity", title: "Source Attribution & Citation Integrity", description: "RAG-grounded outputs must be traceable to their source documents, with cited claims verifiably supported by retrieved content.", chapterId: "C7", standardVersion: "1.0" },
  { id: "C8.1", slug: "c8-1-access-controls-on-memory-and-rag-indices", title: "Access Controls on Memory & RAG Indices", description: "Fine-grained access controls and query-time scope enforcement must be applied to every vector collection.", chapterId: "C8", standardVersion: "1.0" },
  { id: "C8.2", slug: "c8-2-embedding-sanitization-and-validation", title: "Embedding Sanitization & Validation", description: "Content must be pre-screened before vectorization, and memory writes treated as untrusted input, to prevent ingestion of unsafe payloads.", chapterId: "C8", standardVersion: "1.0" },
  { id: "C8.3", slug: "c8-3-memory-expiry-and-revocation", title: "Memory Expiry & Revocation", description: "Retention and revocation must be explicit and enforceable for memory and RAG indices.", chapterId: "C8", standardVersion: "1.0" },
  { id: "C9.1", slug: "c9-1-execution-budgets-loop-control-and-circuit-breakers", title: "Execution Budgets, Loop Control, and Circuit Breakers", description: "Runtime expansion (recursion, concurrency, cost) must be bounded, with safe halting on runaway behavior.", chapterId: "C9", standardVersion: "1.0" },
  { id: "C9.2", slug: "c9-2-high-impact-action-approval-and-irreversibility-controls", title: "High-Impact Action Approval and Irreversibility Controls", description: "Privileged, high-impact, or hard-to-reverse agent actions must require trusted approval checkpoints.", chapterId: "C9", standardVersion: "1.0" },
  { id: "C9.3", slug: "c9-3-component-isolation-and-tool-authorization", title: "Component Isolation and Tool Authorization", description: "Tool and plugin execution, loading, and outputs must be constrained to prevent unauthorized system access and unsafe side effects.", chapterId: "C9", standardVersion: "1.0" },
  { id: "C9.4", slug: "c9-4-agent-and-orchestrator-identity", title: "Agent and Orchestrator Identity", description: "Every action must be attributable and every mutation detectable.", chapterId: "C9", standardVersion: "1.0" },
  { id: "C9.5", slug: "c9-5-agent-authorization-delegation-and-continuous-enforcement", title: "Agent Authorization, Delegation, and Continuous Enforcement", description: "Every action must be authorized at execution time and constrained by scope.", chapterId: "C9", standardVersion: "1.0" },
  { id: "C9.6", slug: "c9-6-shutdown-and-graceful-degradation", title: "Shutdown and Graceful Degradation", description: "Shutdown and graceful degradation paths must remain under human control, with mechanisms that stay reliable and are exercised over time.", chapterId: "C9", standardVersion: "1.0" },
  { id: "C10.1", slug: "c10-1-component-integrity", title: "Component Integrity", description: "Only trusted MCP components must be used, and locally launched servers must be secured.", chapterId: "C10", standardVersion: "1.0" },
  { id: "C10.2", slug: "c10-2-authentication-and-authorization", title: "Authentication & Authorization", description: "Callers must be authenticated and access to MCP servers authorized, following protocol best practices.", chapterId: "C10", standardVersion: "1.0" },
  { id: "C10.3", slug: "c10-3-secure-transport", title: "Secure Transport", description: "MCP communications must be secured following protocol best practices.", chapterId: "C10", standardVersion: "1.0" },
  { id: "C10.4", slug: "c10-4-schema-message-and-input-validation", title: "Schema, Message, and Input Validation", description: "Schema, message, and input validation must be enforced in both MCP servers and clients.", chapterId: "C10", standardVersion: "1.0" },
  { id: "C11.1", slug: "c11-1-model-alignment-safety-and-robustness-testing-and-training", title: "Model Alignment, Safety, and Robustness Testing and Training", description: "Model resilience to manipulated inputs designed to cause misclassification or policy bypass must be increased, primarily through adversarial testing and robustness benchmarking.", chapterId: "C11", standardVersion: "1.0" },
  { id: "C11.2", slug: "c11-2-membership-inference-and-model-inversion-mitigation", title: "Membership-Inference and Model-Inversion Mitigation", description: "The ability to determine whether a specific record was in the training data must be limited, and reconstruction of private training data or sensitive attributes from model outputs prevented.", chapterId: "C11", standardVersion: "1.0" },
  { id: "C11.3", slug: "c11-3-model-extraction-defense", title: "Model-Extraction Defense", description: "Unauthorized model cloning through API abuse must be detected and deterred using rate limiting, query-pattern analysis, and watermarking.", chapterId: "C11", standardVersion: "1.0" },
  { id: "C11.4", slug: "c11-4-model-runtime-anomaly-detection", title: "Model Runtime Anomaly Detection", description: "Manipulated, backdoored, or adversarial data entering the model context at inference time via external sources must be identified and neutralized.", chapterId: "C11", standardVersion: "1.0" },
  { id: "C12.1", slug: "c12-1-request-and-response-logging", title: "Request & Response Logging", description: "AI requests and responses must be logged to create an audit trail and support incident response.", chapterId: "C12", standardVersion: "1.0" },
  { id: "C12.2", slug: "c12-2-detection-and-alerting", title: "Detection and Alerting", description: "AI-specific attack patterns (jailbreak, prompt injection, model extraction, multi-turn trajectory attacks, covert channels over LLM endpoints) must be detected, and security events enriched with AI-specific context so downstream detection and response systems can act on them.", chapterId: "C12", standardVersion: "1.0" },
  { id: "C12.3", slug: "c12-3-model-data-and-performance-drift-detection", title: "Model, Data, and Performance Drift Detection", description: "Drift and degradation across model outputs, input distributions, and data schemas must be monitored to identify quality regressions and security-relevant behavioral shifts.", chapterId: "C12", standardVersion: "1.0" },
  { id: "C12.4", slug: "c12-4-proactive-security-behavior-monitoring", title: "Proactive Security Behavior Monitoring", description: "Security threats arising from proactive (agent-initiated) behavior must be detected and prevented, including pre-execution validation, behavior pattern analysis, and audit trails for approval of security-critical actions.", chapterId: "C12", standardVersion: "1.0" },
  { id: "C12.5", slug: "c12-5-training-data-and-model-lifecycle-audit", title: "Training Data & Model Lifecycle Audit", description: "The provenance and change history of training data, model artifacts, and knowledge sources must be auditable throughout the AI development lifecycle.", chapterId: "C12", standardVersion: "1.0" },
];

/** Lookup a section by its slug. */
export function getSectionBySlug(slug: string): Section | undefined {
  return sections.find((section) => section.slug === slug);
}

/** Return all sections belonging to a chapter. */
export function getSectionsByChapter(chapterId: string): Section[] {
  return sections.filter((section) => section.chapterId === chapterId);
}
